#!/bin/bash

o  -all \
    noise-iir-440 \
    noise-iir-10k \
    noise-iir-15k \
    noise-iir-20k \
    pwm-iir  \
    pwm \
    sine-iir-440 \
    sine-iir-1k \
    sine-iir-5k \
    sine-iir-10k \
    ramp-up-iir-440 \
    ramp-up-iir-1k \
    ramp-up-iir-2k \
    ramp-up-iir-5k \
    ramp-up-iir-10k \
    ramp-up \






