/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ondes.audio;


import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Line;
import javax.sound.sampled.Mixer;

import java.util.*;

import static java.lang.System.out;
import static java.util.stream.Collectors.*;

public class AudioInfo {

    static void all() {
        Mixer.Info[] info= AudioSystem.getMixerInfo();
        Arrays.stream(info)
            .sorted(Comparator.comparing(Object::toString))
            .forEach( mi -> {
                out.println(mi);
                Mixer m = AudioSystem.getMixer(mi);

                out.println("Source lines:");
                Line.Info[] srcLineInfo = m.getSourceLineInfo();
                Arrays.stream(srcLineInfo).forEach(s -> out.println("  "+s));
                out.println("Target lines:");
                Line.Info[] trgLineInfo = m.getTargetLineInfo();
                Arrays.stream(trgLineInfo).forEach(s -> out.println("  "+s));

                out.println("  --");
            });

        out.println("\nShowing all mixers. Say 'in' or 'out' \n" +
            " to see Source or Target mixers respectively");

    }

    static void out() {
        Mixer.Info[] info = AudioSystem.getMixerInfo();
        Arrays.stream(info)
            .sorted(Comparator.comparing(Object::toString))
            .forEach(mi -> {
                Mixer m = AudioSystem.getMixer(mi);
                Line.Info[] srcLineInfo = m.getSourceLineInfo();
                Line.Info[] trgLineInfo = m.getTargetLineInfo();
                if (trgLineInfo.length == 0) return;

                out.println(mi);
                out.println("Source lines:");
                Arrays.stream(srcLineInfo).forEach(s -> out.println("  " + s));
                out.println("Target lines:");
                Arrays.stream(trgLineInfo).forEach(s -> out.println("  " + s));

                out.println("  --");
            });
    }

    static void in() {
        Mixer.Info[] info = AudioSystem.getMixerInfo();
        Arrays.stream(info)
            .sorted(Comparator.comparing(Object::toString))
            .forEach(mi -> {
                Mixer m = AudioSystem.getMixer(mi);
                Line.Info[] srcLineInfo = m.getSourceLineInfo();
                Line.Info[] trgLineInfo = m.getTargetLineInfo();
                if (srcLineInfo.length == 0) return;

                out.println(mi);
                out.println("Source lines:");
                Arrays.stream(srcLineInfo).forEach(s -> out.println("  " + s));
                out.println("Target lines:");
                Arrays.stream(trgLineInfo).forEach(s -> out.println("  " + s));

                out.println("  --");
            });
    }


    public static void main(String[] args) {

        if (args.length == 0) {
            all();

        }
        else {
            if (args[0].equals("out")) out();
            else if (args[0].equals("in")) in();
            else all();
        }
    }

}
